/// Flutter icons RaMCustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RaMCustomIcons
///      fonts:
///       - asset: fonts/RaMCustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RaMCustomIcons {
  RaMCustomIcons._();

  static const _kFontFam = 'RaMCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData rickface1 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rickface2 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortyface2 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortyface1 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
